version: "3.5"
services:
  books_api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3032:3032"
    depends_on:
      - mysql_service
      - redis_service
    environment:
      - REDIS_URL=redis://redis_service
      - MYSQL_HOST=mysql_service
      - MYSQL_USERNAME=test
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=book_api
      - MYSQL_SYNCHRONIZE=true
    networks:
      - books_api_net

  mysql_service:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=book_api
    networks:
      - books_api_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_service:db
    ports:
      - 8081:80
    networks:
      - books_api_net

  redis_service:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - books_api_net

networks:
  books_api_net:
    driver: bridge
